### ISSUE TITLE
unhandled 'getaddrinfo' failure from arweave.net

### ISSUE THREAD

**Issue by alexander-morris** [koii-network/node#8]
![image](https://user-images.githubusercontent.com/37120777/120112294-9adfd380-c14b-11eb-95f2-aa94672792bf.png)

**Comment by AndreVallestero** [comment]
This is likely an internet issue causing the error (DNS wasn't able to resolve arweave.net).

TODO: This isn't really a bug, but it should be handled with a proper error message.
